name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Spongebob
      - name: checkout repo
        uses: actions/checkout@v1
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"