name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: mutliline script
        run: |
          date
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-bash-on-windows:
    runs-on: windows-latest
    steps:
      - name: output current directory
        run: pwd
      - name: output current directory in bash
        run: pwd
        shell: bash
   