name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: echo a string
        run: echo "Hello World!"
        continue-on-error: true
      - name: mutliline script
        run: |
          date
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-bash-on-windows:
    runs-on: windows-latest
    needs: ['run-shell-command']
    steps:
      - name: output current directory in powershell
        run: Get-Location
      - name: output current directory in bash
        run: pwd
        shell: bash
   